apiVersion: v1
kind: StorageClass
metadata:
  name: first-storageclass-aws
provisioner: kubernetes.io/aws-ebs #CSI plugin of cloud provisioner
parametes:
  type: gp3
  iopsPerGB: "3000"
  throughput: "125"
recalimPolicy: Delete
allowVolumeExpansion: true
