apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZiV0Z1WVhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDbHNCdjJrMVF3R25MVGZWRUdhcTJXKzVRU1V2UWtSbUh0dlZhUWJqaXVCSE1FCjVvS0ZsV0FOWlpWQW9WZ0ZrVmxoc1J4cGprT1JoYWdad3hyNnRQbnlxZGhBWUNLWUhNcUF1WFhpam5CdkhlZzcKTndrSFJtS0RxblRrU1JZNmVlTGluSXRQWlUwTnN3Qy9qMVJzNG5DV0hpK0Jvd3hLL2VkQXptLzB2Ym1jTEhVbwpqbzBOOUpTUjFXeExhMy83Q2xuQ3p6VlNZVm5MZVB4V0dVL0dWYURJZkFtdDhlOEFsNlJxbk1mUDlSeGpsZEI3Cjg3Q2paLzRRYXFRSktIU3lVc2hKSFB0UmhIODlEdDB0czlndlVuVTZxWXQzZE5kT3NjOHpMdDVSdExPd2U1OWcKcDd0dE5yZHZmenRWbjUyMmh3VFZaV0p5WWtLUWFqUlVPZUFTeFJZVEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFEb1NTcGZCRzgyS1AzQmxlUDFVSitiT0xpcDViVGkrVm1KNm5OSlBQQVVGRW9uaE1HbTY1Cm9TanhpMGIxdEZWZWNBQkxtcWlGczMwWjhEaDhnbFZMTEk4ZVpoa28rOVIzRXVyUUc1SkZzWEpBQ3plck56WncKODUwZ0FER2piZnNYOXRFR09uT3VjWkZUQWdDSnZFNnY3dWZzQ2x4SkdIakZzOHh4OGo1KzR1VUkxcHgwKzU1awozYTJiYW5ObDR0dWQrS3RFc2lJUFVQcnpwY3hNQ2VhejNBUmEreGdlbFhPRXFHVW1aMVljRDRqL1JJd3ByTXhrCitYaE91UVBRZHdjV3I3MXB3QWRiKzlDeG9JOU94bFM0amVBeHY1Z3A2YVVxMzZtODg4cGRVSjF1ejVndEJoZ3UKdnZKa1FZSjcxWnhENXU2ck9rQjdzZ3lldC9BSk5IZllXQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: example.com/serving
  usages:
    - digital signature
    - key encipherment
    - server auth
