apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"] # The resource type to control access to
    verbs: ["get", "watch", "list"] # Allowed operations on the resource
