apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: myapp
type: Opaque # generic secret type
data:
  # Values must be base64 encoded
  username: YWRtaW4= # "admin" in base64
  password: cGFzc3dvcmQ= # "password" in base64
  api_token: dG9rZW4xMjM0NTY= # "token123456" in base64
