apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-0
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessmodes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: delete
  storageClassName: local-storage # storage class this pv belongs to
  hostPath:
    path: /root/kubernetes_content/mongodb/storage-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-1
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessmodes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: delete
  storageClassName: local-storage # storage class this pv belongs to
  hostPath:
    path: /root/kubernetes_content/mongodb/storage-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-2
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessmodes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: delete
  storageClassName: local-storage # storage class this pv belongs to
  hostPath:
    path: /root/kubernetes_content/mongodb/storage-2
