apiVersion: v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: headless # headless service
  replicas: 3 # number of pod
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  volumeClaimTemplates:
    - metadata:
        name: local-storage-pv
      spec:
        accessModes: ["ReadWriteOnce"] # should match with pv
        storageClassName:
          local-storage # should match with pv
          # then while creation it will pick pv associated with storageclass
        resources:
          requests:
            storage: 500Mi
